title: That's Not Metal Archive
description: >
  This site is an unofficial collection of show notes and links from the That’s
  Not Metal podcast.
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - README.md
  - yarn.lock
include:
  - _pages
google_analytics: UA-83926181-1
permalink: /show/:year-:month-:day-:title/

collections:
  specials:
    output: true
    permalink: /special/:year-:month-:day-:title/
  extras:
    output: true
    permalink: /tnm-extra/:year-:month-:day-:title/

# Pagination
paginate: 10
paginate_path: "/shows/page-:num/"

# Site specific
twitter: https://twitter.com/notmetalpod
facebook: https://www.facebook.com/thatsnotmetalpodcast/

# Styles
sass:
  style: compressed
