[build]
  command = "npm run build"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.36"
  HUGO_ENV = "production"
  NODE_VERSION = "--lts=carbon"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.36"
  NODE_VERSION = "--lts=carbon"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.36"
  NODE_VERSION = "--lts=carbon"
