[build]
  command = "npm run build"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.31.1"
  HUGO_ENV = "production"
  NODE_VERSION = "8.9.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.31.1"
  NODE_VERSION = "8.9.2"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.31.1"
  NODE_VERSION = "8.9.2"
